import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/globals.css";
import "../styles/shared/general.css";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Amazon | Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  header,
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${roboto.className} antialiased`}>
          {header}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
